import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, ClipboardCopy, ExternalLink, Eye, FileText, Plus, Save, Trash2 } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { useToast } from '../../context/ToastContext'
import { Badge, Button, Card, EmptyState, ErrorState, Input, Modal, PageHeader, Select, Spinner, Textarea } from '../../components/ui'

type FormRow={id:string;slug:string;title:string;description:string;success_message:string;is_published:boolean;created_at?:string}
type QuestionRow={id:string;form_id:string;label:string;help_text:string;question_type:string;options:string[];is_required:boolean;is_active:boolean;sort_order:number}
type Submission={id:string;applicant_name:string;applicant_email:string;status:string;created_at:string}
const TYPES=['text','textarea','email','phone','number','select','radio','checkbox']
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
export default function ApplicationFormsPage(){
 const{notify}=useToast();const[forms,setForms]=useState<FormRow[]>([]);const[form,setForm]=useState<FormRow|null>(null);const[questions,setQuestions]=useState<QuestionRow[]>([]);const[submissions,setSubmissions]=useState<Submission[]>([]);const[tab,setTab]=useState<'builder'|'submissions'>('builder');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[creating,setCreating]=useState(false);const[newTitle,setNewTitle]=useState('')
 async function loadForms(prefer?:string){setLoading(true);setError('');const{data,error:e}=await supabase.from('application_forms').select('*').order('created_at');if(e){setError(e.message);setLoading(false);return}const list=(data??[]) as FormRow[];setForms(list);const chosen=list.find(x=>x.id===(prefer||form?.id))||list[0]||null;setForm(chosen);if(chosen)await loadForm(chosen);setLoading(false)}
 async function loadForm(chosen:FormRow){setForm(chosen);const[{data:q,error:qe},{data:s,error:se}]=await Promise.all([supabase.from('application_form_questions').select('*').eq('form_id',chosen.id).order('sort_order'),supabase.from('application_form_submissions').select('id,applicant_name,applicant_email,status,created_at').eq('form_id',chosen.id).order('created_at',{ascending:false})]);if(qe||se)setError(qe?.message||se?.message||'Unable to load');else{setQuestions((q||[]) as QuestionRow[]);setSubmissions((s||[]) as Submission[])}}
 useEffect(()=>{loadForms()},[])
 const publicUrl=form?`${window.location.origin}/apply/${form.slug}`:''
 async function createForm(){const title=newTitle.trim();if(!title)return;setSaving(true);let slug=slugify(title)||`form-${Date.now()}`;const{data,error:e}=await supabase.from('application_forms').insert({title,slug,description:'Complete this form and our team will review your submission.',success_message:'Thank you. Your response has been received.',is_published:false}).select('*').single();setSaving(false);if(e)notify(e.message,'error');else{notify('New form created.');setCreating(false);setNewTitle('');await loadForms(data.id)}}
 function patch(id:string,changes:Partial<QuestionRow>){setQuestions(q=>q.map(x=>x.id===id?{...x,...changes}:x))}
 function move(i:number,d:number){const t=i+d;if(t<0||t>=questions.length)return;const c=[...questions];[c[i],c[t]]=[c[t],c[i]];setQuestions(c.map((q,n)=>({...q,sort_order:n+1})))}
 async function add(){if(!form)return;const{data,error:e}=await supabase.from('application_form_questions').insert({form_id:form.id,label:'New question',question_type:'text',options:[],is_required:false,is_active:true,sort_order:questions.length+1}).select('*').single();if(e)notify(e.message,'error');else setQuestions(q=>[...q,data as QuestionRow])}
 async function remove(id:string){if(!confirm('Delete this question?'))return;const{error:e}=await supabase.from('application_form_questions').delete().eq('id',id);if(e)notify(e.message,'error');else setQuestions(q=>q.filter(x=>x.id!==id))}
 async function removeForm(){if(!form||!confirm(`Delete “${form.title}” and its questions/submissions?`))return;const{error:e}=await supabase.from('application_forms').delete().eq('id',form.id);if(e)notify(e.message,'error');else{notify('Form deleted.');setForm(null);await loadForms()}}
 async function save(){if(!form)return;setSaving(true);const{error:fe}=await supabase.from('application_forms').update({title:form.title,slug:form.slug,description:form.description,success_message:form.success_message,is_published:form.is_published}).eq('id',form.id);const payload=questions.map((q,i)=>({...q,sort_order:i+1}));const{error:qe}=payload.length?await supabase.from('application_form_questions').upsert(payload):{error:null};setSaving(false);if(fe||qe)notify(fe?.message||qe?.message||'Unable to save','error');else{notify('Form saved.');loadForms(form.id)}}
 if(loading)return <Spinner label="Loading forms"/>;if(error)return <ErrorState message={error} onRetry={()=>loadForms()}/>
 return <><PageHeader eyebrow="Admissions" title="Public forms" description="Create separate shareable forms, then open and edit each form independently." action={<Button onClick={()=>setCreating(true)}><Plus className="h-4 w-4"/>Create form</Button>}/>
 <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside><Card><h2 className="font-semibold">Your forms</h2><div className="mt-3 space-y-2">{forms.map(f=><button key={f.id} onClick={()=>loadForm(f)} className={`w-full rounded-xl border p-3 text-left ${form?.id===f.id?'border-brand-300 bg-brand-50':'border-canvas-line'}`}><div className="flex justify-between gap-2"><span className="font-medium">{f.title}</span><Badge tone={f.is_published?'success':'neutral'}>{f.is_published?'Live':'Draft'}</Badge></div><p className="mt-1 text-xs text-ink-soft">/{f.slug}</p></button>)}{!forms.length&&<p className="text-sm text-ink-muted">No forms yet.</p>}</div></Card></aside>
 <section>{!form?<EmptyState icon={FileText} title="Create your first form" description="Each form gets its own public link and editable questions." action={<Button onClick={()=>setCreating(true)}>Create form</Button>}/>:<><div className="mb-4 flex flex-wrap gap-2"><Button variant={tab==='builder'?'primary':'outline'} onClick={()=>setTab('builder')}><FileText className="h-4 w-4"/>Builder</Button><Button variant={tab==='submissions'?'primary':'outline'} onClick={()=>setTab('submissions')}><Eye className="h-4 w-4"/>Submissions <Badge>{submissions.length}</Badge></Button><Button variant="outline" onClick={()=>{navigator.clipboard.writeText(publicUrl);notify('Public link copied.')}}><ClipboardCopy className="h-4 w-4"/>Copy link</Button><Button variant="outline" onClick={()=>window.open(publicUrl,'_blank')}><ExternalLink className="h-4 w-4"/>Preview</Button></div>
 {tab==='submissions'?<Card><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Applicant</th><th className="p-3">Email</th><th className="p-3">Status</th><th className="p-3">Submitted</th></tr></thead><tbody>{submissions.map(s=><tr key={s.id} className="border-b"><td className="p-3 font-medium">{s.applicant_name||'Unnamed'}</td><td className="p-3">{s.applicant_email||'—'}</td><td className="p-3"><Badge>{s.status}</Badge></td><td className="p-3">{new Date(s.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></Card>:<div className="space-y-5"><Card className="grid gap-4"><Input label="Form title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><Input label="Public URL slug" value={form.slug} onChange={e=>setForm({...form,slug:slugify(e.target.value)})}/><Textarea label="Introduction" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Textarea label="Success message" value={form.success_message} onChange={e=>setForm({...form,success_message:e.target.value})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/>Publicly available</label></Card>
 {questions.map((q,i)=><Card key={q.id}><div className="mb-4 flex justify-between"><Badge tone="brand">Question {i+1}</Badge><div className="flex"><Button size="sm" variant="ghost" onClick={()=>move(i,-1)}><ArrowUp className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={()=>move(i,1)}><ArrowDown className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={()=>remove(q.id)}><Trash2 className="h-4 w-4 text-rose-600"/></Button></div></div><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Input label="Question" value={q.label} onChange={e=>patch(q.id,{label:e.target.value})}/></div><Select label="Answer type" value={q.question_type} onChange={e=>patch(q.id,{question_type:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</Select><Input label="Help text" value={q.help_text||''} onChange={e=>patch(q.id,{help_text:e.target.value})}/>{['select','radio','checkbox'].includes(q.question_type)&&<div className="md:col-span-2"><Textarea label="Options — one per line" value={(q.options||[]).join('\n')} onChange={e=>patch(q.id,{options:e.target.value.split('\n').filter(Boolean)})}/></div>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={q.is_required} onChange={e=>patch(q.id,{is_required:e.target.checked})}/>Required</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={q.is_active} onChange={e=>patch(q.id,{is_active:e.target.checked})}/>Visible</label></div></Card>)}
 <div className="sticky bottom-4 flex justify-between rounded-2xl border bg-white/95 p-3 shadow-lg"><div className="flex gap-2"><Button variant="outline" onClick={add}><Plus className="h-4 w-4"/>Add question</Button><Button variant="ghost" onClick={removeForm}><Trash2 className="h-4 w-4"/>Delete form</Button></div><Button loading={saving} onClick={save}><Save className="h-4 w-4"/>Save form</Button></div></div>}</>}</section></div>
 <Modal open={creating} onClose={()=>setCreating(false)} title="Create a new public form" footer={<><Button variant="outline" onClick={()=>setCreating(false)}>Cancel</Button><Button onClick={createForm} loading={saving} disabled={!newTitle.trim()}>Create form</Button></>}><Input label="Form name" value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Coaching application"/></Modal></>
}
