import { useState } from 'react'
import { Megaphone, Plus, Image as ImageIcon } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { uploadAcademyMedia } from '../lib/media'
import { useAsyncData } from '../lib/useAsyncData'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { isStaff } from '../lib/access'
import { Badge, Button, Card, EmptyState, ErrorState, Input, Modal, PageHeader, Select, Spinner, Textarea } from '../components/ui'
import { formatDate, readableError } from '../lib/utils'
import type { Announcement, AnnouncementAudience, Batch, Course } from '../lib/types'

const EMPTY = { title:'', summary:'', message:'', banner_url:'', audience:'global' as AnnouncementAudience, course_id:'', batch_id:'', expires_at:'' }
export default function AnnouncementsPage(){
 const {profile,role}=useAuth(); const {notify}=useToast(); const staff=isStaff(role)
 const [creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false)
 const [selected,setSelected]=useState<Announcement|null>(null); const [draft,setDraft]=useState({...EMPTY})
 const state=useAsyncData<{announcements:Announcement[];courses:Course[];batches:Batch[]}>(async()=>{
  const [a,c,b]=await Promise.all([supabase.from('announcements').select('*').order('publish_at',{ascending:false}),supabase.from('courses').select('id,title,slug,level').order('sort_order'),supabase.from('batches').select('id,code,name').eq('is_active',true).order('code')]); if(a.error) throw a.error
  return {announcements:(a.data??[]) as Announcement[],courses:(c.data??[]) as Course[],batches:(b.data??[]) as Batch[]}
 },[profile?.id])
 const upload=async(file?:File)=>{if(!file)return;setUploading(true);try{setDraft({...draft,banner_url:await uploadAcademyMedia(file,'announcements')});notify('Banner uploaded.')}catch(e){notify(readableError(e),'error')}finally{setUploading(false)}}
 const publish=async()=>{setSaving(true);try{const {error}=await supabase.from('announcements').insert({title:draft.title.trim(),summary:draft.summary.trim(),message:draft.message.trim(),banner_url:draft.banner_url||null,audience:draft.audience,course_id:draft.audience==='course'?draft.course_id||null:null,batch_id:draft.audience==='batch'?draft.batch_id||null:null,author_id:profile?.id??null,expires_at:draft.expires_at?new Date(draft.expires_at).toISOString():null});if(error)throw error;notify('Announcement published.');setCreating(false);setDraft({...EMPTY});state.reload()}catch(e){notify(readableError(e),'error')}finally{setSaving(false)}}
 const retire=async(id:string)=>{const {error}=await supabase.from('announcements').update({is_active:false}).eq('id',id);if(error)notify(readableError(error),'error');else{notify('Announcement retired.');state.reload()}}
 if(state.loading)return <Spinner label="Loading announcements"/>; if(state.error)return <ErrorState message={state.error} onRetry={state.reload}/>
 const rows=state.data!.announcements
 return <><PageHeader title="Announcements" description={staff?'Publish polished academy news with optional banner images.':'News and important updates from VA Success Academy.'} action={staff&&<Button onClick={()=>setCreating(true)}><Plus className="h-4 w-4"/>Post announcement</Button>}/>
 {rows.length===0?<EmptyState icon={Megaphone} title="No announcements yet" description="Important academy news will appear here."/>:<div className="grid gap-6 md:grid-cols-2">{rows.map(item=><button key={item.id} type="button" onClick={()=>setSelected(item)} className="text-left"><Card className={`h-full overflow-hidden p-0 transition hover:-translate-y-0.5 hover:shadow-pop ${!item.is_active?'opacity-60':''}`}>{item.banner_url?<img src={item.banner_url} alt="" className="h-48 w-full object-cover"/>:<div className="flex h-40 items-center justify-center bg-gradient-to-br from-brand-700 via-brand-600 to-violet-400 text-white"><Megaphone className="h-12 w-12 opacity-80"/></div>}<div className="p-5"><div className="flex items-center gap-2"><Badge tone={item.audience==='global'?'brand':'info'}>{item.audience}</Badge>{!item.is_active&&<Badge>Retired</Badge>}</div><h2 className="mt-3 text-xl font-bold text-ink">{item.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-ink-muted">{item.summary||item.message}</p><div className="mt-4 flex items-center justify-between border-t border-canvas-line pt-4"><span className="text-xs text-ink-soft">{formatDate(item.publish_at)}</span><span className="text-sm font-semibold text-brand-700">Read announcement</span></div></div></Card></button>)}</div>}
 <Modal open={!!selected} onClose={()=>setSelected(null)} wide title="Announcement" footer={<>{staff&&selected?.is_active&&<Button variant="outline" onClick={()=>{retire(selected.id);setSelected(null)}}>Retire</Button>}<Button onClick={()=>setSelected(null)}>Close</Button></>}>{selected&&<article className="overflow-hidden rounded-2xl border border-canvas-line bg-white">{selected.banner_url?<img src={selected.banner_url} alt="" className="max-h-80 w-full object-cover"/>:<div className="h-32 bg-gradient-to-r from-brand-700 to-violet-500"/>}<div className="p-6 sm:p-8"><Badge tone="brand">Academy news</Badge><h1 className="mt-4 text-3xl font-bold text-ink">{selected.title}</h1>{selected.summary&&<p className="mt-3 text-lg leading-7 text-ink-muted">{selected.summary}</p>}<p className="mt-6 whitespace-pre-line leading-7 text-ink">{selected.message}</p><p className="mt-8 border-t border-canvas-line pt-4 text-xs text-ink-soft">Published {formatDate(selected.publish_at)}{selected.expires_at?` · Expires ${formatDate(selected.expires_at)}`:''}</p></div></article>}</Modal>
 <Modal open={creating} onClose={()=>setCreating(false)} wide title="Publish an announcement" description="Create a professional news-style post for the academy." footer={<><Button variant="outline" onClick={()=>setCreating(false)}>Cancel</Button><Button onClick={publish} loading={saving} disabled={!draft.title.trim()||!draft.message.trim()}>Publish</Button></>}><div className="space-y-4"><Input label="Headline" required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><Textarea label="Short summary" value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})} hint="Shown on the announcement card."/><Textarea label="Full article" required className="min-h-[220px]" value={draft.message} onChange={e=>setDraft({...draft,message:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><Input label="Banner image URL" type="url" value={draft.banner_url} onChange={e=>setDraft({...draft,banner_url:e.target.value})}/><div><label className="field-label">Upload banner</label><label className="mt-1 flex h-11 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-brand-300 bg-brand-50 text-sm font-medium text-brand-700"><ImageIcon className="h-4 w-4"/>{uploading?'Uploading...':'Choose image'}<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div><Select label="Audience" value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value as AnnouncementAudience})}><option value="global">Everyone</option><option value="coaches">Coaches only</option><option value="course">One course</option><option value="batch">One batch</option></Select>{draft.audience==='course'?<Select label="Course" value={draft.course_id} onChange={e=>setDraft({...draft,course_id:e.target.value})}><option value="">Choose course</option>{state.data!.courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select>:draft.audience==='batch'?<Select label="Batch" value={draft.batch_id} onChange={e=>setDraft({...draft,batch_id:e.target.value})}><option value="">Choose batch</option>{state.data!.batches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</Select>:<div/>}<Input label="Expires on" type="date" value={draft.expires_at} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></div>{draft.banner_url&&<img src={draft.banner_url} alt="Banner preview" className="h-44 w-full rounded-xl object-cover"/>}</div></Modal>
 </>
}
