import { useMemo, useState } from 'react'
import { Bell, Check, Mail, Plus, Video, ShieldQuestion, ExternalLink } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAsyncData } from '../lib/useAsyncData'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { Badge, Button, Card, EmptyState, ErrorState, Input, Modal, PageHeader, Select, Spinner, Textarea } from '../components/ui'
import { readableError, relativeDays } from '../lib/utils'
import type { Notification, Profile } from '../lib/types'

type Audience = 'individual'|'all'|'students'|'coaches'
const EMPTY = { audience:'individual' as Audience, user_id:'', title:'', body:'', notification_type:'email', sender_name:'', sender_email:'', action_label:'Open invitation', external_url:'', details:'' }

export default function NotificationsPage(){
 const {profile,role}=useAuth(); const {notify}=useToast(); const [selected,setSelected]=useState<Notification|null>(null); const [creating,setCreating]=useState(false); const [saving,setSaving]=useState(false); const [draft,setDraft]=useState({...EMPTY})
 const state=useAsyncData<{rows:Notification[];users:Pick<Profile,'id'|'full_name'|'email'|'role'>[]}>(async()=>{if(!profile)return{rows:[],users:[]};const [notes,users]=await Promise.all([supabase.from('notifications').select('*').eq('user_id',profile.id).order('created_at',{ascending:false}).limit(100),supabase.from('profiles').select('id,full_name,email,role').eq('is_active',true).order('full_name')]);if(notes.error)throw notes.error;return{rows:(notes.data??[]) as Notification[],users:(users.data??[]) as Pick<Profile,'id'|'full_name'|'email'|'role'>[]}},[profile?.id])
 const rows=state.data?.rows??[];const unread=useMemo(()=>rows.filter(n=>!n.is_read).length,[rows])
 const allowedUsers=useMemo(()=>{const all=state.data?.users??[];if(!profile)return[];if(role==='owner'||role==='manager')return all.filter(u=>u.id!==profile.id);if(role==='coach')return all.filter(u=>u.id!==profile.id&&(u.role==='coach'||u.role==='student'));if(role==='student')return all.filter(u=>u.role==='coach');return[]},[state.data?.users,profile,role])
 const audienceOptions=role==='owner'||role==='manager'?['individual','all','students','coaches'] as Audience[]:role==='coach'?['individual','students','coaches'] as Audience[]:['individual'] as Audience[]
 const markRead=async(item:Notification)=>{if(!item.is_read)await supabase.from('notifications').update({is_read:true}).eq('id',item.id);setSelected({...item,is_read:true});state.reload()}
 const markAllRead=async()=>{if(!profile)return;const{error}=await supabase.from('notifications').update({is_read:true}).eq('user_id',profile.id).eq('is_read',false);if(error)return notify(readableError(error),'error');notify('All notifications marked as read.');state.reload()}
 const send=async()=>{if(!profile||!draft.title.trim()||!draft.body.trim())return;setSaving(true);try{let recipients=allowedUsers;if(draft.audience==='individual')recipients=allowedUsers.filter(u=>u.id===draft.user_id);else if(draft.audience==='students')recipients=allowedUsers.filter(u=>u.role==='student');else if(draft.audience==='coaches')recipients=allowedUsers.filter(u=>u.role==='coach');if(!recipients.length)throw new Error('Choose at least one allowed recipient.');const payload=recipients.map(u=>({user_id:u.id,title:draft.title.trim(),body:draft.body.trim(),notification_type:draft.notification_type,sender_name:draft.sender_name||profile.full_name,sender_email:draft.sender_email||profile.email,action_label:draft.action_label||'Open',external_url:draft.external_url||null,details:draft.details||null,created_by:profile.id,audience:draft.audience}));const{error}=await supabase.from('notifications').insert(payload);if(error)throw error;notify(`Notification sent to ${recipients.length} recipient${recipients.length===1?'':'s'}.`);setCreating(false);setDraft({...EMPTY})}catch(e){notify(readableError(e),'error')}finally{setSaving(false)}}
 if(state.loading)return <Spinner label="Loading notifications"/>;if(state.error)return <ErrorState message={state.error} onRetry={state.reload}/>
 const IconFor=({type}:{type?:string})=>{const I=type==='zoom_invitation'?Video:type==='access_request'?ShieldQuestion:Mail;return <I className="h-5 w-5"/>}
 return <><PageHeader title="Notifications" description={unread?`${unread} unread message${unread===1?'':'s'}`:'You are all caught up.'} action={<><Button onClick={()=>setCreating(true)}><Plus className="h-4 w-4"/>Send notification</Button>{unread>0&&<Button variant="outline" onClick={markAllRead}><Check className="h-4 w-4"/>Mark all read</Button>}</>}/>
 {rows.length===0?<EmptyState icon={Bell} title="Nothing here yet" description="Invitations, requests and personal updates will appear here."/>:<div className="grid gap-3">{rows.map(item=><button key={item.id} type="button" onClick={()=>markRead(item)} className="text-left"><Card className={`transition hover:border-brand-200 ${!item.is_read?'border-brand-200 bg-brand-50/30':''}`}><div className="flex gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-100 text-brand-700"><IconFor type={item.notification_type}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><h2 className="font-semibold text-ink">{item.title}</h2>{!item.is_read&&<Badge tone="brand">New</Badge>}<Badge>{(item.notification_type??'email').replace('_',' ')}</Badge></div><p className="mt-1 line-clamp-2 text-sm text-ink-muted">{item.body}</p><p className="mt-2 text-xs text-ink-soft">{item.sender_name?`From ${item.sender_name}`:'VA Success Academy'} · {relativeDays(item.created_at)}</p></div><span className="text-sm font-medium text-brand-700">Open</span></div></Card></button>)}</div>}
 <Modal open={!!selected} onClose={()=>setSelected(null)} wide title={selected?.title??''} description={selected?.sender_name?`From ${selected.sender_name}${selected.sender_email?` <${selected.sender_email}>`:''}`:'VA Success Academy'} footer={<Button variant="outline" onClick={()=>setSelected(null)}>Close</Button>}>{selected&&<div className="overflow-hidden rounded-2xl border bg-white"><div className="bg-gradient-to-r from-brand-700 to-brand-500 px-6 py-6 text-white"><Badge className="border-white/20 bg-white/10 text-white">{(selected.notification_type??'email').replace('_',' ')}</Badge><h2 className="mt-3 text-2xl font-bold">{selected.title}</h2></div><div className="space-y-4 p-6"><p className="whitespace-pre-line leading-7">{selected.body}</p>{selected.details&&<div className="rounded-xl bg-canvas p-4 whitespace-pre-line text-sm">{selected.details}</div>}{selected.external_url&&<a href={selected.external_url} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 rounded-xl bg-brand-600 px-5 text-sm font-semibold text-white">{selected.action_label||'Open link'}<ExternalLink className="h-4 w-4"/></a>}</div></div>}</Modal>
 <Modal open={creating} onClose={()=>setCreating(false)} wide title="Send notification" description="Audience choices follow your role permissions." footer={<><Button variant="outline" onClick={()=>setCreating(false)}>Cancel</Button><Button onClick={send} loading={saving} disabled={!draft.title.trim()||!draft.body.trim()||(draft.audience==='individual'&&!draft.user_id)}>Send notification</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Select label="Audience" value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value as Audience,user_id:''})}>{audienceOptions.map(a=><option key={a} value={a}>{a==='individual'?'One person':a==='all'?'Everyone':a==='students'?'All students':'All coaches'}</option>)}</Select>{draft.audience==='individual'?<Select label={role==='student'?'Coach':'Recipient'} required value={draft.user_id} onChange={e=>setDraft({...draft,user_id:e.target.value})}><option value="">Choose a person</option>{allowedUsers.map(u=><option key={u.id} value={u.id}>{u.full_name} — {u.email} ({u.role})</option>)}</Select>:<div/>}<Select label="Type" value={draft.notification_type} onChange={e=>setDraft({...draft,notification_type:e.target.value})}><option value="email">Email-style message</option><option value="zoom_invitation">Zoom invitation</option><option value="access_request">Access request</option><option value="general">General update</option></Select><div className="sm:col-span-2"><Input label="Subject" required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></div><Input label="Sender name" value={draft.sender_name} onChange={e=>setDraft({...draft,sender_name:e.target.value})}/><Input label="Sender email" type="email" value={draft.sender_email} onChange={e=>setDraft({...draft,sender_email:e.target.value})}/><div className="sm:col-span-2"><Textarea label="Message" required value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></div><div className="sm:col-span-2"><Textarea label="Event or request details" value={draft.details} onChange={e=>setDraft({...draft,details:e.target.value})}/></div><Input label="Button text" value={draft.action_label} onChange={e=>setDraft({...draft,action_label:e.target.value})}/><Input label="Zoom or external link" type="url" value={draft.external_url} onChange={e=>setDraft({...draft,external_url:e.target.value})}/></div></Modal></>
}
